# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fantasy_cricket.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Title Label
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        # Players Group Box
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 351, 481))
        self.groupBox.setObjectName("groupBox")
        
        # Players List Widget
        self.listWidgetPlayers = QtWidgets.QListWidget(self.groupBox)
        self.listWidgetPlayers.setGeometry(QtCore.QRect(10, 80, 331, 391))
        self.listWidgetPlayers.setObjectName("listWidgetPlayers")
        
        # Radio Buttons for Player Categories
        self.radioButtonBAT = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonBAT.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radioButtonBAT.setChecked(True)
        self.radioButtonBAT.setObjectName("radioButtonBAT")
        
        self.radioButtonBOW = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonBOW.setGeometry(QtCore.QRect(90, 30, 82, 17))
        self.radioButtonBOW.setObjectName("radioButtonBOW")
        
        self.radioButtonAR = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonAR.setGeometry(QtCore.QRect(170, 30, 82, 17))
        self.radioButtonAR.setObjectName("radioButtonAR")
        
        self.radioButtonWK = QtWidgets.QRadioButton(self.groupBox)
        self.radioButtonWK.setGeometry(QtCore.QRect(250, 30, 82, 17))
        self.radioButtonWK.setObjectName("radioButtonWK")
        
        # Selected Players Group Box
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(420, 60, 351, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        
        # Selected Players List Widget
        self.listWidgetSelected = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidgetSelected.setGeometry(QtCore.QRect(10, 30, 331, 441))
        self.listWidgetSelected.setObjectName("listWidgetSelected")
        
        # Points Labels
        self.labelPointsAvailable = QtWidgets.QLabel(self.centralwidget)
        self.labelPointsAvailable.setGeometry(QtCore.QRect(420, 550, 151, 16))
        self.labelPointsAvailable.setObjectName("labelPointsAvailable")
        
        self.labelPointsUsed = QtWidgets.QLabel(self.centralwidget)
        self.labelPointsUsed.setGeometry(QtCore.QRect(620, 550, 151, 16))
        self.labelPointsUsed.setObjectName("labelPointsUsed")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Menu Bar
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        
        MainWindow.setMenuBar(self.menubar)
        
        # Status Bar
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        # Actions
        self.actionNew_Team = QtWidgets.QAction(MainWindow)
        self.actionNew_Team.setObjectName("actionNew_Team")
        
        self.actionOpen_Team = QtWidgets.QAction(MainWindow)
        self.actionOpen_Team.setObjectName("actionOpen_Team")
        
        self.actionSave_Team = QtWidgets.QAction(MainWindow)
        self.actionSave_Team.setObjectName("actionSave_Team")
        
        self.actionEvaluate_Team = QtWidgets.QAction(MainWindow)
        self.actionEvaluate_Team.setObjectName("actionEvaluate_Team")
        
        # Add actions to menu
        self.menuManage_Teams.addAction(self.actionNew_Team)
        self.menuManage_Teams.addAction(self.actionOpen_Team)
        self.menuManage_Teams.addAction(self.actionSave_Team)
        self.menuManage_Teams.addAction(self.actionEvaluate_Team)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fantasy Cricket"))
        self.label.setText(_translate("MainWindow", "FANTASY CRICKET"))
        self.groupBox.setTitle(_translate("MainWindow", "Players"))
        self.radioButtonBAT.setText(_translate("MainWindow", "BAT"))
        self.radioButtonBOW.setText(_translate("MainWindow", "BOW"))
        self.radioButtonAR.setText(_translate("MainWindow", "AR"))
        self.radioButtonWK.setText(_translate("MainWindow", "WK"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Selected Players (0/11)"))
        self.labelPointsAvailable.setText(_translate("MainWindow", "Points Available: 1000"))
        self.labelPointsUsed.setText(_translate("MainWindow", "Points Used: 0"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNew_Team.setText(_translate("MainWindow", "New Team"))
        self.actionOpen_Team.setText(_translate("MainWindow", "Open Team"))
        self.actionSave_Team.setText(_translate("MainWindow", "Save Team"))
        self.actionEvaluate_Team.setText(_translate("MainWindow", "Evaluate Team"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())